{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f0e968e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import torch\n",
    "import torchvision.transforms as transforms\n",
    "from torchvision.models import resnet50\n",
    "from PIL import Image\n",
    "import numpy as np\n",
    "from sklearn.metrics.pairwise import cosine_similarity"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bcbfce90",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/vsoma_ogh6dsk/Documents/Courses/Spring_2025/.venv/lib/python3.13/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.\n",
      "  warnings.warn(\n",
      "/Users/vsoma_ogh6dsk/Documents/Courses/Spring_2025/.venv/lib/python3.13/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.\n",
      "  warnings.warn(msg)\n",
      "Downloading: \"https://download.pytorch.org/models/resnet50-0676ba61.pth\" to /Users/vsoma_ogh6dsk/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth\n",
      "100%|██████████| 97.8M/97.8M [00:11<00:00, 9.14MB/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Similarity with ariel_image_231.jpeg: 0.5719\n",
      "Similarity with ariel_image_203.jpeg: 0.6079\n",
      "Similarity with ariel_image_238.jpeg: 0.6159\n",
      "Similarity with ariel_image_161.jpeg: 0.5546\n",
      "Similarity with ariel_image_298.jpeg: 0.5960\n",
      "Similarity with arura_image_216.jpeg: 0.5873\n",
      "Similarity with arura_image_212.jpeg: 0.5367\n",
      "Similarity with arura_image_207.jpeg: 0.5582\n",
      "Similarity with arura_image_214.jpeg: 0.6044\n",
      "Similarity with arura_image_270.jpeg: 0.6060\n",
      "Similarity with tiana_image_3.jpeg: 0.6244\n",
      "Similarity with tiana_image_174.jpeg: 0.6660\n",
      "Similarity with tiana_image_14.jpeg: 0.6589\n",
      "Similarity with tiana_image_224.jpeg: 0.6188\n",
      "Similarity with tiana_image_276.jpeg: 0.6125\n",
      "Similarity with merida_image_23.jpeg: 0.6057\n",
      "Similarity with merida_image_126.jpeg: 0.6387\n",
      "Similarity with merida_image_14.jpeg: 0.6435\n",
      "Similarity with merida_image_115.jpeg: 0.5984\n",
      "Similarity with merida_image_46.jpeg: 0.6596\n",
      "Similarity with belle_image_1.jpeg: 0.6528\n",
      "Similarity with belle_image_278.jpeg: 0.6219\n",
      "Similarity with belle_image_18.jpeg: 0.6182\n",
      "Similarity with belle_image_270.jpeg: 0.7000\n",
      "Similarity with belle_image_110.jpeg: 0.6198\n",
      "Similarity with Snow White_image_160.jpeg: 0.5908\n",
      "Similarity with Snow White_image_239.jpeg: 0.5997\n",
      "Similarity with Snow White_image_219.jpeg: 0.4995\n",
      "Similarity with Snow White_image_385.jpeg: 0.6141\n",
      "Similarity with Snow White_image_240.jpeg: 0.5808\n",
      "Similarity with elsa_image_18.jpeg: 0.5881\n",
      "Similarity with elsa_image_17.jpeg: 0.6896\n",
      "Similarity with elsa_image_85.jpeg: 0.6238\n",
      "Similarity with elsa_image_11.jpeg: 0.6359\n",
      "Similarity with elsa_image_19.jpeg: 0.6500\n",
      "Similarity with jasmine_image_36.jpeg: 0.6208\n",
      "Similarity with jasmine_image_24.jpeg: 0.6884\n",
      "Similarity with jasmine_image_480.jpeg: 0.5935\n",
      "Similarity with jasmine_image_334.jpeg: 0.6051\n",
      "Similarity with jasmine_image_484.jpeg: 0.6025\n",
      "Similarity with Raponzel_image_36.jpeg: 0.6220\n",
      "Similarity with Raponzel_image_410.jpeg: 0.6140\n",
      "Similarity with Raponzel_image_271.jpeg: 0.5924\n",
      "Similarity with Raponzel_image_268.jpeg: 0.6040\n",
      "Similarity with Raponzel_image_115.jpeg: 0.5750\n",
      "Similarity with anna_image_294.jpeg: 0.5662\n",
      "Similarity with anna_image_292.jpeg: 0.6718\n",
      "Similarity with anna_image_293.jpeg: 0.7088\n",
      "Similarity with anna_image_209.jpeg: 0.6337\n",
      "Similarity with anna_image_127.jpeg: 0.6844\n",
      "\n",
      "Most similar image: /Users/vsoma_ogh6dsk/Documents/Courses/Spring_2025/data_hacks_2025/Code_space/../Datasets/anna/anna_image_293.jpeg (Similarity: 0.7088)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "'/Users/vsoma_ogh6dsk/Documents/Courses/Spring_2025/data_hacks_2025/Code_space/../Datasets/anna/anna_image_293.jpeg'"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "# Load pretrained model and remove classification head\n",
    "model = resnet50(pretrained=True)\n",
    "model = torch.nn.Sequential(*list(model.children())[:-1])  # Remove last FC layer\n",
    "model.eval()\n",
    "\n",
    "# Preprocessing pipeline\n",
    "transform = transforms.Compose([\n",
    "    transforms.Resize((224, 224)),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(\n",
    "        mean=[0.485, 0.456, 0.406],  # ImageNet mean\n",
    "        std=[0.229, 0.224, 0.225]    # ImageNet std\n",
    "    )\n",
    "])\n",
    "\n",
    "def extract_features(img_path):\n",
    "    \"\"\"Extract feature vector from an image file.\"\"\"\n",
    "    img = Image.open(img_path).convert('RGB')   x\n",
    "    img_tensor = transform(img).unsqueeze(0)  # Add batch dimension\n",
    "    with torch.no_grad():\n",
    "        features = model(img_tensor).squeeze()  # Remove batch and flatten\n",
    "    return features.numpy()\n",
    "\n",
    "def find_most_similar(query_img_path, dataset_folder):\n",
    "    \"\"\"Find image in dataset_folder most similar to query image.\"\"\"\n",
    "         \n",
    "    query_features = extract_features(query_img_path).reshape(1, -1)\n",
    "\n",
    "    max_similarity = -1\n",
    "    most_similar_img = None\n",
    "\n",
    "    for subdir, _, files in os.walk(dataset_folder):\n",
    "        # Select 5 random files from each subfolder\n",
    "        selected_files = np.random.choice(files, size=min(5, len(files)), replace=False)\n",
    "        for filename in selected_files:\n",
    "            file_path = os.path.join(subdir, filename)\n",
    "            if os.path.isfile(file_path):\n",
    "                dataset_features = extract_features(file_path).reshape(1, -1)\n",
    "                similarity = cosine_similarity(query_features, dataset_features)[0][0]\n",
    "                print(f\"Similarity with {filename}: {similarity:.4f}\")\n",
    "\n",
    "                if similarity > max_similarity:\n",
    "                    max_similarity = similarity\n",
    "                    most_similar_img = file_path\n",
    "\n",
    "    print(f\"\\nMost similar image: {most_similar_img} (Similarity: {max_similarity:.4f})\")\n",
    "    return most_similar_img\n",
    "\n",
    "# Example usage\n",
    "input_image_dir = os.path.join(os.getcwd(), '..', 'imput_samp')\n",
    "input_image_name = 'image2.jpg'\n",
    "input_image_path = os.path.join(input_image_dir, input_image_name)\n",
    "dataset_dir = os.path.join(os.getcwd(), '..', 'Datasets')\n",
    "find_most_similar(input_image_path, dataset_dir)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "bd73450a",
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "Traceback (most recent call last):\n  File \"c:\\Users\\quydz\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 73, in <module>\n    from tensorflow.python._pywrap_tensorflow_internal import *\nImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.\n\n\nFailed to load the native TensorFlow runtime.\nSee https://www.tensorflow.org/install/errors for some common causes and solutions.\nIf you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\quydz\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py:73\u001b[0m\n\u001b[0;32m     72\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 73\u001b[0m   \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtensorflow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpython\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_pywrap_tensorflow_internal\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n\u001b[0;32m     74\u001b[0m \u001b[38;5;66;03m# This try catch logic is because there is no bazel equivalent for py_extension.\u001b[39;00m\n\u001b[0;32m     75\u001b[0m \u001b[38;5;66;03m# Externally in opensource we must enable exceptions to load the shared object\u001b[39;00m\n\u001b[0;32m     76\u001b[0m \u001b[38;5;66;03m# by exposing the PyInit symbols with pybind. This error will only be\u001b[39;00m\n\u001b[0;32m     77\u001b[0m \u001b[38;5;66;03m# caught internally or if someone changes the name of the target _pywrap_tensorflow_internal.\u001b[39;00m\n\u001b[0;32m     78\u001b[0m \n\u001b[0;32m     79\u001b[0m \u001b[38;5;66;03m# This logic is used in other internal projects using py_extension.\u001b[39;00m\n",
      "\u001b[1;31mImportError\u001b[0m: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[13], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mos\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mrandom\u001b[39;00m\n\u001b[1;32m----> 3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mdeepface\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m DeepFace\n\u001b[0;32m      5\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mget_random_images_from_subdirs\u001b[39m(dataset_folder, sample_size\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m10\u001b[39m, valid_exts\u001b[38;5;241m=\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m.jpg\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m.jpeg\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m.png\u001b[39m\u001b[38;5;124m\"\u001b[39m)):\n\u001b[0;32m      6\u001b[0m     all_image_paths \u001b[38;5;241m=\u001b[39m []\n",
      "File \u001b[1;32mc:\\Users\\quydz\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\deepface\\DeepFace.py:15\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mnumpy\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mnp\u001b[39;00m\n\u001b[0;32m     14\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpandas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mpd\u001b[39;00m\n\u001b[1;32m---> 15\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtensorflow\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtf\u001b[39;00m\n\u001b[0;32m     17\u001b[0m \u001b[38;5;66;03m# package dependencies\u001b[39;00m\n\u001b[0;32m     18\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mdeepface\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcommons\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m package_utils, folder_utils\n",
      "File \u001b[1;32mc:\\Users\\quydz\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\tensorflow\\__init__.py:40\u001b[0m\n\u001b[0;32m     37\u001b[0m _os\u001b[38;5;241m.\u001b[39menviron\u001b[38;5;241m.\u001b[39msetdefault(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mENABLE_RUNTIME_UPTIME_TELEMETRY\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m1\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     39\u001b[0m \u001b[38;5;66;03m# Do not remove this line; See https://github.com/tensorflow/tensorflow/issues/42596\u001b[39;00m\n\u001b[1;32m---> 40\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtensorflow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpython\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m pywrap_tensorflow \u001b[38;5;28;01mas\u001b[39;00m _pywrap_tensorflow  \u001b[38;5;66;03m# pylint: disable=unused-import\u001b[39;00m\n\u001b[0;32m     41\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtensorflow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpython\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtools\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m module_util \u001b[38;5;28;01mas\u001b[39;00m _module_util\n\u001b[0;32m     42\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtensorflow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpython\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutil\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mlazy_loader\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m KerasLazyLoader \u001b[38;5;28;01mas\u001b[39;00m _KerasLazyLoader\n",
      "File \u001b[1;32mc:\\Users\\quydz\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py:88\u001b[0m\n\u001b[0;32m     86\u001b[0m     sys\u001b[38;5;241m.\u001b[39msetdlopenflags(_default_dlopen_flags)\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m:\n\u001b[1;32m---> 88\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(\n\u001b[0;32m     89\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mtraceback\u001b[38;5;241m.\u001b[39mformat_exc()\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m     90\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mFailed to load the native TensorFlow runtime.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m     91\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mSee https://www.tensorflow.org/install/errors \u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m     92\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mfor some common causes and solutions.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m     93\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mIf you need help, create an issue \u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m     94\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mat https://github.com/tensorflow/tensorflow/issues \u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m     95\u001b[0m       \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mand include the entire stack trace above this error message.\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m     97\u001b[0m \u001b[38;5;66;03m# pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long\u001b[39;00m\n",
      "\u001b[1;31mImportError\u001b[0m: Traceback (most recent call last):\n  File \"c:\\Users\\quydz\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 73, in <module>\n    from tensorflow.python._pywrap_tensorflow_internal import *\nImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.\n\n\nFailed to load the native TensorFlow runtime.\nSee https://www.tensorflow.org/install/errors for some common causes and solutions.\nIf you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message."
     ]
    }
   ],
   "source": [
    "import os\n",
    "import random\n",
    "from deepface import DeepFace\n",
    "\n",
    "def get_random_images_from_subdirs(dataset_folder, sample_size=10, valid_exts=(\".jpg\", \".jpeg\", \".png\")):\n",
    "    all_image_paths = []\n",
    "    for root, _, files in os.walk(dataset_folder):\n",
    "        for file in files:\n",
    "            if file.lower().endswith(valid_exts):\n",
    "                all_image_paths.append(os.path.join(root, file))\n",
    "\n",
    "    if len(all_image_paths) == 0:\n",
    "        raise ValueError(\"No images found in dataset folder.\")\n",
    "\n",
    "    return random.sample(all_image_paths, min(sample_size, len(all_image_paths)))\n",
    "\n",
    "def find_most_similar_face(query_img_path, dataset_folder, model_name=\"Facenet\", sample_size=10):\n",
    "    sample_images = get_random_images_from_subdirs(dataset_folder, sample_size=sample_size)\n",
    "\n",
    "    best_match = None\n",
    "    best_score = float(\"inf\")  # Lower distance is better\n",
    "\n",
    "    for img_path in sample_images:\n",
    "        try:\n",
    "            result = DeepFace.verify(img1_path=query_img_path,\n",
    "                                     img2_path=img_path,\n",
    "                                     model_name=model_name,\n",
    "                                     enforce_detection=False)\n",
    "            distance = result['distance']\n",
    "            print(f\"Similarity with {os.path.basename(img_path)}: Distance = {distance:.4f}\")\n",
    "            if distance < best_score:\n",
    "                best_score = distance\n",
    "                best_match = img_path\n",
    "        except Exception as e:\n",
    "            print(f\"Skipped {img_path}: {e}\")\n",
    "\n",
    "    print(f\"\\n✅ Most similar face: {best_match} (Distance: {best_score:.4f})\")\n",
    "    return best_match\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7f89b551",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
